"""
Equilibrium Map SQL Exporter

Exports all equilibrium maps for all metal-ligand pairs in the VLM table to a single SQL file.

SQL Schema:
- eq_map_collection: one row per metal-ligand pair
- eq_map: one row per condition iteration  
- eq_network: one row per connected component
- eq_node: one row per VLM entry in a network
- eq_edge: one row per edge (shared species)
- eq_node_species: junction table for species per node (LHS/RHS)
- eq_edge_species: junction table for shared species per edge

The SQL output can be imported into SQLite for later pipeline stages.

Usage:
    python equilibrium_map_sql_exporter.py
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import pandas as pd

# =============================================================================
# Logging configuration
# =============================================================================

logger = logging.getLogger(__name__)

def setup_logging(level: int = logging.INFO, log_file: Optional[Path] = None) -> None:
    """Configure logging for the SQL exporter.
    
    Args:
        level: Logging level (default: INFO)
        log_file: Optional path to log file
    """
    formatter = logging.Formatter(
        '%(asctime)s | %(levelname)-8s | %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    
    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    console_handler.setLevel(level)
    
    # Configure logger
    logger.setLevel(level)
    logger.handlers.clear()
    logger.addHandler(console_handler)
    
    # File handler if specified
    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        file_handler = logging.FileHandler(log_file, encoding='utf-8')
        file_handler.setFormatter(formatter)
        file_handler.setLevel(level)
        logger.addHandler(file_handler)

# Import the builder and data structures
from equilibrium_map_builder_v3 import (
    build_equilibrium_maps_for_pair,
    load_vlm_data,
    load_beta_definitions,
    load_metals,
    load_ligands,
    get_metal_name,
    get_ligand_name,
    VLM_COLS,
    CONSTANT_TYPE_K,
)
from equilibrium_map_helpers import (
    EquilibriumNode,
    EquilibriumEdge,
    EquilibriumNetwork,
    ConditionBin,
    MetalLigandEquilibriumMap,
    MetalLigandEquilibriumMapCollection,
    CONSTANT_TYPE_NAMES,
    extract_species_from_beta_definition,
)


# =============================================================================
# Path configuration
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
OUTPUT_DIR = BASE_DIR / "_output" / "pip2a_equilibrium_map_sql"   # stand-alone runs only; created on demand

DEFAULT_SQL_PATH = OUTPUT_DIR / "equilibrium_maps.db"
DEBUG_REPORT_PATH = OUTPUT_DIR / "equilibrium_map_debug_report.json"
NON_CONVERGED_CSV_PATH = OUTPUT_DIR / "non_converged_vlm_ids.csv"
NO_SPECIES_CSV_PATH = OUTPUT_DIR / "no_species_vlm_ids.csv"


# =============================================================================
# SQL Schema
# =============================================================================

SQL_SCHEMA = """
-- Equilibrium Map SQL Schema
-- Generated by equilibrium_map_sql_exporter.py

-- Pragma for better performance
PRAGMA journal_mode=WAL;
PRAGMA synchronous=NORMAL;

-- =============================================================================
-- Collection table: one row per metal-ligand pair
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_map_collection (
    collection_id INTEGER PRIMARY KEY AUTOINCREMENT,
    metal_id INTEGER NOT NULL,
    ligand_id INTEGER NOT NULL,
    metal_name TEXT,
    ligand_name TEXT,
    total_entries INTEGER DEFAULT 0,
    total_networks INTEGER DEFAULT 0,
    iterations_count INTEGER DEFAULT 0,
    unassigned_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(metal_id, ligand_id)
);

-- =============================================================================
-- Map table: one row per condition iteration
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_map (
    map_id INTEGER PRIMARY KEY AUTOINCREMENT,
    collection_id INTEGER NOT NULL,
    map_key TEXT NOT NULL,
    iteration INTEGER DEFAULT 0,
    -- Condition bin
    condition_temperature REAL,
    condition_ionic_strength REAL,
    condition_temp_min REAL,
    condition_temp_max REAL,
    condition_ionic_min REAL,
    condition_ionic_max REAL,
    -- Counts
    entry_count INTEGER DEFAULT 0,
    network_count INTEGER DEFAULT 0,
    stray_count INTEGER DEFAULT 0,
    FOREIGN KEY (collection_id) REFERENCES eq_map_collection(collection_id),
    UNIQUE(collection_id, map_key)
);

-- =============================================================================
-- Network table: one row per connected component
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_network (
    network_db_id INTEGER PRIMARY KEY AUTOINCREMENT,
    map_id INTEGER NOT NULL,
    network_id INTEGER NOT NULL,  -- Local network ID within the map
    node_count INTEGER DEFAULT 0,
    edge_count INTEGER DEFAULT 0,
    FOREIGN KEY (map_id) REFERENCES eq_map(map_id),
    UNIQUE(map_id, network_id)
);

-- =============================================================================
-- Node table: one row per VLM entry in a network
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_node (
    node_db_id INTEGER PRIMARY KEY AUTOINCREMENT,
    network_db_id INTEGER NOT NULL,
    vlm_id INTEGER NOT NULL,
    entry_index INTEGER,
    metal_id INTEGER NOT NULL,
    ligand_id INTEGER NOT NULL,
    beta_definition_id INTEGER NOT NULL,
    beta_definition_name TEXT,
    equation_python TEXT,
    constant_type TEXT,
    constant_value REAL,
    temperature REAL,
    ionic_strength REAL,
    is_duplicate INTEGER DEFAULT 0,
    used_in_map INTEGER DEFAULT 1,
    FOREIGN KEY (network_db_id) REFERENCES eq_network(network_db_id)
);

-- Index for fast VLM lookups
CREATE INDEX IF NOT EXISTS idx_eq_node_vlm_id ON eq_node(vlm_id);
CREATE INDEX IF NOT EXISTS idx_eq_node_beta_id ON eq_node(beta_definition_id);

-- =============================================================================
-- Node species junction table
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_node_species (
    node_db_id INTEGER NOT NULL,
    species TEXT NOT NULL,
    side TEXT NOT NULL,  -- 'LHS', 'RHS', or 'BOTH'
    FOREIGN KEY (node_db_id) REFERENCES eq_node(node_db_id),
    PRIMARY KEY (node_db_id, species, side)
);

-- =============================================================================
-- Edge table: one row per edge (shared species)
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_edge (
    edge_db_id INTEGER PRIMARY KEY AUTOINCREMENT,
    network_db_id INTEGER NOT NULL,
    node1_vlm_id INTEGER NOT NULL,
    node2_vlm_id INTEGER NOT NULL,
    FOREIGN KEY (network_db_id) REFERENCES eq_network(network_db_id)
);

-- =============================================================================
-- Edge species junction table
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_edge_species (
    edge_db_id INTEGER NOT NULL,
    species TEXT NOT NULL,
    FOREIGN KEY (edge_db_id) REFERENCES eq_edge(edge_db_id),
    PRIMARY KEY (edge_db_id, species)
);

-- =============================================================================
-- Network species junction table (all species in network)
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_network_species (
    network_db_id INTEGER NOT NULL,
    species TEXT NOT NULL,
    FOREIGN KEY (network_db_id) REFERENCES eq_network(network_db_id),
    PRIMARY KEY (network_db_id, species)
);

-- =============================================================================
-- Stray VLM IDs table (entries not assigned to networks)
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_map_stray (
    map_id INTEGER NOT NULL,
    vlm_id INTEGER NOT NULL,
    FOREIGN KEY (map_id) REFERENCES eq_map(map_id),
    PRIMARY KEY (map_id, vlm_id)
);

-- =============================================================================
-- Unassigned VLM IDs table (entries not assigned after all iterations)
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_collection_unassigned (
    collection_id INTEGER NOT NULL,
    vlm_id INTEGER NOT NULL,
    FOREIGN KEY (collection_id) REFERENCES eq_map_collection(collection_id),
    PRIMARY KEY (collection_id, vlm_id)
);

-- =============================================================================
-- Debug/metadata table
-- =============================================================================
CREATE TABLE IF NOT EXISTS eq_export_metadata (
    key TEXT PRIMARY KEY,
    value TEXT
);
"""


# =============================================================================
# Debug Report Data Structure
# =============================================================================

@dataclass
class DebugReport:
    """Debug report for VLM coverage."""
    
    # Counts
    total_vlm_entries: int = 0
    total_vlm_k_type: int = 0
    unique_metal_ligand_pairs: int = 0
    
    # Coverage
    vlm_assigned_to_networks: int = 0
    vlm_stray: int = 0
    vlm_unassigned: int = 0
    
    # Validation
    valid_beta_count: int = 0
    invalid_beta_vlm_ids: List[int] = None
    valid_metal_count: int = 0
    invalid_metal_vlm_ids: List[int] = None
    valid_ligand_count: int = 0
    invalid_ligand_vlm_ids: List[int] = None
    
    # No-species betas (skipped)
    no_species_beta_ids: List[int] = None
    no_species_vlm_ids: List[int] = None
    no_species_vlm_count: int = 0
    
    # Errors
    processing_errors: List[Dict[str, Any]] = None
    
    # Timing
    start_time: str = ""
    end_time: str = ""
    duration_seconds: float = 0.0
    
    def __post_init__(self):
        if self.invalid_beta_vlm_ids is None:
            self.invalid_beta_vlm_ids = []
        if self.invalid_metal_vlm_ids is None:
            self.invalid_metal_vlm_ids = []
        if self.invalid_ligand_vlm_ids is None:
            self.invalid_ligand_vlm_ids = []
        if self.no_species_beta_ids is None:
            self.no_species_beta_ids = []
        if self.no_species_vlm_ids is None:
            self.no_species_vlm_ids = []
        if self.processing_errors is None:
            self.processing_errors = []
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_vlm_entries": self.total_vlm_entries,
            "total_vlm_k_type": self.total_vlm_k_type,
            "unique_metal_ligand_pairs": self.unique_metal_ligand_pairs,
            "vlm_assigned_to_networks": self.vlm_assigned_to_networks,
            "vlm_stray": self.vlm_stray,
            "vlm_unassigned": self.vlm_unassigned,
            "coverage_rate": (
                self.vlm_assigned_to_networks / self.total_vlm_k_type * 100
                if self.total_vlm_k_type > 0 else 0
            ),
            "valid_beta_count": self.valid_beta_count,
            "invalid_beta_vlm_count": len(self.invalid_beta_vlm_ids),
            "valid_metal_count": self.valid_metal_count,
            "invalid_metal_vlm_count": len(self.invalid_metal_vlm_ids),
            "valid_ligand_count": self.valid_ligand_count,
            "invalid_ligand_vlm_count": len(self.invalid_ligand_vlm_ids),
            "no_species_beta_count": len(self.no_species_beta_ids),
            "no_species_vlm_count": self.no_species_vlm_count,
            "processing_errors_count": len(self.processing_errors),
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_seconds": self.duration_seconds,
        }


# =============================================================================
# SQLite Exporter
# =============================================================================

class EquilibriumMapSQLExporter:
    """Exports equilibrium maps to SQLite database."""
    
    def __init__(self, db_path: Path = DEFAULT_SQL_PATH):
        self.db_path = db_path
        self.conn: Optional[sqlite3.Connection] = None
        self.debug_report = DebugReport()
        
        # Tracking sets
        self._assigned_vlm_ids: Set[int] = set()
        self._stray_vlm_ids: Set[int] = set()
        self._unassigned_vlm_ids: Set[int] = set()
        self._no_species_vlm_set: Set[int] = set()
    
    def open(self) -> None:
        """Open database connection and create schema."""
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Remove existing file if it exists
        if self.db_path.exists():
            self.db_path.unlink()
        
        self.conn = sqlite3.connect(str(self.db_path))
        self.conn.executescript(SQL_SCHEMA)
        self.conn.commit()
    
    def close(self) -> None:
        """Close database connection."""
        if self.conn:
            self.conn.close()
            self.conn = None
    
    def validate_vlm_entries(self) -> None:
        """Validate all VLM entries for valid beta, metal, ligand references."""
        logger.info("validate_vlm_entries: Starting VLM validation...")
        
        vlm_df = load_vlm_data()
        beta_df = load_beta_definitions()
        metals_df = load_metals()
        ligands_df = load_ligands()
        
        self.debug_report.total_vlm_entries = len(vlm_df)
        logger.debug(f"  Loaded {len(vlm_df)} total VLM entries")
        
        # Filter K-type only
        k_type_mask = vlm_df[VLM_COLS["constant_type"]] == CONSTANT_TYPE_K
        k_type_vlm = vlm_df[k_type_mask].copy()
        self.debug_report.total_vlm_k_type = len(k_type_vlm)
        logger.debug(f"  K-type entries: {len(k_type_vlm)}")
        
        # Check beta references
        beta_col = VLM_COLS["beta_id"]
        beta_ids = set(beta_df.index) if "beta_definitionID" in beta_df.columns else set(beta_df["beta_definitionID"])
        invalid_beta_mask = ~k_type_vlm[beta_col].isin(beta_ids)
        self.debug_report.invalid_beta_vlm_ids = list(k_type_vlm.loc[invalid_beta_mask, "verkn_ligand_metalID"])
        self.debug_report.valid_beta_count = len(beta_ids)
        logger.debug(f"  Beta validation: {len(beta_ids)} valid IDs, {len(self.debug_report.invalid_beta_vlm_ids)} invalid refs")
        
        # Check metal references
        metal_col = VLM_COLS["metal_id"]
        metal_ids = set(metals_df.index) if "metalID" in metals_df.columns else set(metals_df["metalID"])
        invalid_metal_mask = ~k_type_vlm[metal_col].isin(metal_ids)
        self.debug_report.invalid_metal_vlm_ids = list(k_type_vlm.loc[invalid_metal_mask, "verkn_ligand_metalID"])
        self.debug_report.valid_metal_count = len(metal_ids)
        logger.debug(f"  Metal validation: {len(metal_ids)} valid IDs, {len(self.debug_report.invalid_metal_vlm_ids)} invalid refs")
        
        # Check ligand references
        ligand_col = VLM_COLS["ligand_id"]
        ligand_ids = set(ligands_df.index) if "ligandenID" in ligands_df.columns else set(ligands_df["ligandenID"])
        invalid_ligand_mask = ~k_type_vlm[ligand_col].isin(ligand_ids)
        self.debug_report.invalid_ligand_vlm_ids = list(k_type_vlm.loc[invalid_ligand_mask, "verkn_ligand_metalID"])
        self.debug_report.valid_ligand_count = len(ligand_ids)
        logger.debug(f"  Ligand validation: {len(ligand_ids)} valid IDs, {len(self.debug_report.invalid_ligand_vlm_ids)} invalid refs")
        
        # Detect betas with no species (these VLM entries can never form nodes)
        logger.debug("  Detecting betas with no species...")
        no_species_beta_ids = set()
        for beta_id in beta_df.index:
            beta_row = beta_df.loc[beta_id]
            lhs, rhs, all_sp = extract_species_from_beta_definition(beta_row, int(beta_id))
            if len(all_sp) == 0:
                no_species_beta_ids.add(float(beta_id))
        
        self.debug_report.no_species_beta_ids = [int(b) for b in no_species_beta_ids]
        
        # Find VLM entries referencing no-species betas
        no_species_vlm_mask = k_type_vlm[beta_col].astype(float).isin(no_species_beta_ids)
        self.debug_report.no_species_vlm_ids = list(k_type_vlm.loc[no_species_vlm_mask, "verkn_ligand_metalID"])
        self.debug_report.no_species_vlm_count = len(self.debug_report.no_species_vlm_ids)
        self._no_species_vlm_set = set(self.debug_report.no_species_vlm_ids)
        
        logger.info(f"validate_vlm_entries: Validation complete")
        logger.info(f"  Total VLM entries: {self.debug_report.total_vlm_entries}")
        logger.info(f"  K-type VLM entries: {self.debug_report.total_vlm_k_type}")
        logger.info(f"  Invalid beta refs: {len(self.debug_report.invalid_beta_vlm_ids)}")
        logger.info(f"  Invalid metal refs: {len(self.debug_report.invalid_metal_vlm_ids)}")
        logger.info(f"  Invalid ligand refs: {len(self.debug_report.invalid_ligand_vlm_ids)}")
        logger.info(f"  No-species betas: {len(no_species_beta_ids)} (affects {self.debug_report.no_species_vlm_count} VLM entries)")
        
        print(f"Validation complete:")
        print(f"  Total VLM entries: {self.debug_report.total_vlm_entries}")
        print(f"  K-type VLM entries: {self.debug_report.total_vlm_k_type}")
        print(f"  Invalid beta refs: {len(self.debug_report.invalid_beta_vlm_ids)}")
        print(f"  Invalid metal refs: {len(self.debug_report.invalid_metal_vlm_ids)}")
        print(f"  Invalid ligand refs: {len(self.debug_report.invalid_ligand_vlm_ids)}")
        print(f"  No-species betas: {len(no_species_beta_ids)} (affects {self.debug_report.no_species_vlm_count} VLM entries)")
    
    def get_unique_metal_ligand_pairs(self) -> List[Tuple[int, int]]:
        """Get all unique metal-ligand pairs from VLM table (K-type only)."""
        vlm_df = load_vlm_data()
        
        # Filter K-type only
        k_type_mask = vlm_df[VLM_COLS["constant_type"]] == CONSTANT_TYPE_K
        k_type_vlm = vlm_df[k_type_mask]
        
        # Get unique pairs
        metal_col = VLM_COLS["metal_id"]
        ligand_col = VLM_COLS["ligand_id"]
        
        pairs = k_type_vlm[[metal_col, ligand_col]].drop_duplicates()
        result = list(pairs.itertuples(index=False, name=None))
        
        self.debug_report.unique_metal_ligand_pairs = len(result)
        return result
    
    def export_collection(self, collection: MetalLigandEquilibriumMapCollection) -> int:
        """Export a collection to the database.
        
        Returns:
            collection_id from the database
        """
        logger.debug(f"export_collection: M={collection.metal_id}, L={collection.ligand_id} - "
                     f"{collection.total_entries} entries, {len(collection.maps)} maps, "
                     f"{collection.total_networks} networks")
        
        cursor = self.conn.cursor()
        
        # Insert collection
        cursor.execute("""
            INSERT INTO eq_map_collection (
                metal_id, ligand_id, metal_name, ligand_name,
                total_entries, total_networks, iterations_count, unassigned_count
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            collection.metal_id,
            collection.ligand_id,
            collection.metal_name,
            collection.ligand_name,
            collection.total_entries,
            collection.total_networks,
            collection.iterations_count,
            len(collection.unassigned_vlm_ids),
        ))
        collection_id = cursor.lastrowid
        
        # Insert unassigned VLM IDs
        for vlm_id in collection.unassigned_vlm_ids:
            cursor.execute("""
                INSERT INTO eq_collection_unassigned (collection_id, vlm_id)
                VALUES (?, ?)
            """, (collection_id, vlm_id))
            self._unassigned_vlm_ids.add(vlm_id)
        
        # Insert each map
        for map_key, eq_map in collection.maps.items():
            self._export_map(cursor, collection_id, map_key, eq_map)
        
        self.conn.commit()
        return collection_id
    
    def _export_map(
        self,
        cursor: sqlite3.Cursor,
        collection_id: int,
        map_key: str,
        eq_map: MetalLigandEquilibriumMap,
    ) -> int:
        """Export a single map."""
        # Condition data
        cond = eq_map.condition
        cond_temp = cond.temperature if cond else None
        cond_ionic = cond.ionic_strength if cond else None
        cond_temp_min = cond.temp_range[0] if cond else None
        cond_temp_max = cond.temp_range[1] if cond else None
        cond_ionic_min = cond.ionic_range[0] if cond else None
        cond_ionic_max = cond.ionic_range[1] if cond else None
        iteration = cond.iteration if cond else 0
        
        cursor.execute("""
            INSERT INTO eq_map (
                collection_id, map_key, iteration,
                condition_temperature, condition_ionic_strength,
                condition_temp_min, condition_temp_max,
                condition_ionic_min, condition_ionic_max,
                entry_count, network_count, stray_count
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            collection_id, map_key, iteration,
            cond_temp, cond_ionic,
            cond_temp_min, cond_temp_max,
            cond_ionic_min, cond_ionic_max,
            len(eq_map.source_vlm_ids),
            len(eq_map.networks),
            len(eq_map.stray_vlm_ids),
        ))
        map_id = cursor.lastrowid
        
        # Insert stray VLM IDs
        for vlm_id in eq_map.stray_vlm_ids:
            cursor.execute("""
                INSERT INTO eq_map_stray (map_id, vlm_id)
                VALUES (?, ?)
            """, (map_id, vlm_id))
            self._stray_vlm_ids.add(vlm_id)
        
        # Insert networks
        for network_id, network in eq_map.networks.items():
            self._export_network(cursor, map_id, network)
        
        return map_id
    
    def _export_network(
        self,
        cursor: sqlite3.Cursor,
        map_id: int,
        network: EquilibriumNetwork,
    ) -> int:
        """Export a single network."""
        cursor.execute("""
            INSERT INTO eq_network (map_id, network_id, node_count, edge_count)
            VALUES (?, ?, ?, ?)
        """, (
            map_id,
            network.network_id,
            len(network.nodes),
            len(network.edges),
        ))
        network_db_id = cursor.lastrowid
        
        # Insert network species
        for species in network.all_species:
            cursor.execute("""
                INSERT INTO eq_network_species (network_db_id, species)
                VALUES (?, ?)
            """, (network_db_id, species))
        
        # Insert nodes
        vlm_to_node_db_id = {}
        for node in network.nodes:
            node_db_id = self._export_node(cursor, network_db_id, node)
            vlm_to_node_db_id[node.vlm_id] = node_db_id
            self._assigned_vlm_ids.add(node.vlm_id)
        
        # Insert edges
        for edge in network.edges:
            self._export_edge(cursor, network_db_id, edge)
        
        return network_db_id
    
    def _export_node(
        self,
        cursor: sqlite3.Cursor,
        network_db_id: int,
        node: EquilibriumNode,
    ) -> int:
        """Export a single node."""
        cursor.execute("""
            INSERT INTO eq_node (
                network_db_id, vlm_id, entry_index,
                metal_id, ligand_id, beta_definition_id,
                beta_definition_name, equation_python,
                constant_type, constant_value,
                temperature, ionic_strength,
                is_duplicate, used_in_map
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            network_db_id,
            node.vlm_id,
            node.entry_index,
            node.metal_id,
            node.ligand_id,
            node.beta_definition_id,
            node.beta_definition_name,
            node.equation_python,
            node.constant_type,
            node.constant_value,
            node.temperature,
            node.ionic_strength,
            1 if node.is_duplicate else 0,
            1 if node.used_in_map else 0,
        ))
        node_db_id = cursor.lastrowid
        
        # Insert species
        for species in node.lhs_species:
            cursor.execute("""
                INSERT OR IGNORE INTO eq_node_species (node_db_id, species, side)
                VALUES (?, ?, 'LHS')
            """, (node_db_id, species))
        
        for species in node.rhs_species:
            cursor.execute("""
                INSERT OR IGNORE INTO eq_node_species (node_db_id, species, side)
                VALUES (?, ?, 'RHS')
            """, (node_db_id, species))
        
        return node_db_id
    
    def _export_edge(
        self,
        cursor: sqlite3.Cursor,
        network_db_id: int,
        edge: EquilibriumEdge,
    ) -> int:
        """Export a single edge."""
        cursor.execute("""
            INSERT INTO eq_edge (network_db_id, node1_vlm_id, node2_vlm_id)
            VALUES (?, ?, ?)
        """, (network_db_id, edge.node1_vlm_id, edge.node2_vlm_id))
        edge_db_id = cursor.lastrowid
        
        # Insert shared species
        for species in edge.shared_species:
            cursor.execute("""
                INSERT INTO eq_edge_species (edge_db_id, species)
                VALUES (?, ?)
            """, (edge_db_id, species))
        
        return edge_db_id
    
    def export_all(self, max_pairs: Optional[int] = None, max_iterations: int = 10000) -> DebugReport:
        """Export all metal-ligand pairs to the database.
        
        Args:
            max_pairs: Optional limit on number of pairs to process (for testing)
            max_iterations: Maximum iterations per pair (default 10000)
            
        Returns:
            DebugReport with coverage statistics
        """
        logger.info("export_all: Starting full export...")
        self.debug_report.start_time = datetime.now().isoformat()
        start_time = time.time()
        
        # Validate first (also detects no-species betas)
        print("Validating VLM entries...")
        self.validate_vlm_entries()
        
        # Get all pairs
        pairs = self.get_unique_metal_ligand_pairs()
        logger.info(f"export_all: Found {len(pairs)} unique metal-ligand pairs")
        
        if max_pairs:
            pairs = pairs[:max_pairs]
            logger.info(f"export_all: Limited to first {max_pairs} pairs")
        
        print(f"\nProcessing {len(pairs)} metal-ligand pairs (max_iterations={max_iterations})...")
        logger.info(f"export_all: Processing {len(pairs)} pairs with max_iterations={max_iterations}")
        
        # Process each pair
        pairs_with_data = 0
        pairs_empty = 0
        pairs_error = 0
        
        for i, (metal_id, ligand_id) in enumerate(pairs):
            if (i + 1) % 500 == 0 or i == 0:
                elapsed = time.time() - start_time
                rate = (i + 1) / elapsed if elapsed > 0 else 0
                eta = (len(pairs) - i - 1) / rate if rate > 0 else 0
                print(f"  [{i + 1}/{len(pairs)}] metal={metal_id}, ligand={ligand_id} | {elapsed:.0f}s elapsed, ETA {eta:.0f}s")
                logger.info(f"export_all: Progress [{i + 1}/{len(pairs)}] - {pairs_with_data} with data, {pairs_empty} empty, {pairs_error} errors")
            
            try:
                collection = build_equilibrium_maps_for_pair(
                    metal_id=metal_id,
                    ligand_id=ligand_id,
                    max_iterations=max_iterations,
                )
                
                if collection.total_entries > 0:
                    self.export_collection(collection)
                    pairs_with_data += 1
                else:
                    pairs_empty += 1
                    
            except Exception as e:
                pairs_error += 1
                logger.warning(f"export_all: Error processing M={metal_id}, L={ligand_id}: {e}")
                self.debug_report.processing_errors.append({
                    "metal_id": metal_id,
                    "ligand_id": ligand_id,
                    "error": str(e),
                })
        
        logger.info(f"export_all: Finished processing - {pairs_with_data} with data, {pairs_empty} empty, {pairs_error} errors")
        
        # Finalize debug report
        self.debug_report.vlm_assigned_to_networks = len(self._assigned_vlm_ids)
        self.debug_report.vlm_stray = len(self._stray_vlm_ids)
        self.debug_report.vlm_unassigned = len(self._unassigned_vlm_ids)
        
        self.debug_report.end_time = datetime.now().isoformat()
        self.debug_report.duration_seconds = time.time() - start_time
        
        logger.info(f"export_all: Complete in {self.debug_report.duration_seconds:.1f}s")
        logger.info(f"  VLM assigned to networks: {self.debug_report.vlm_assigned_to_networks}")
        logger.info(f"  VLM stray (duplicates): {self.debug_report.vlm_stray}")
        logger.info(f"  VLM unassigned: {self.debug_report.vlm_unassigned}")
        
        # Save metadata
        cursor = self.conn.cursor()
        for key, value in self.debug_report.to_dict().items():
            cursor.execute("""
                INSERT INTO eq_export_metadata (key, value) VALUES (?, ?)
            """, (key, json.dumps(value)))
        self.conn.commit()
        
        return self.debug_report
    
    def save_debug_report(self, path: Path = DEBUG_REPORT_PATH) -> None:
        """Save debug report to JSON file."""
        report_dict = self.debug_report.to_dict()
        
        # Add detailed lists
        report_dict["invalid_beta_vlm_ids"] = self.debug_report.invalid_beta_vlm_ids[:100]
        report_dict["invalid_metal_vlm_ids"] = self.debug_report.invalid_metal_vlm_ids[:100]
        report_dict["invalid_ligand_vlm_ids"] = self.debug_report.invalid_ligand_vlm_ids[:100]
        report_dict["no_species_beta_ids"] = self.debug_report.no_species_beta_ids
        report_dict["processing_errors"] = self.debug_report.processing_errors[:100]
        
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(report_dict, f, indent=2)
        
        print(f"Debug report saved to: {path}")
    
    def save_non_converged_csv(self, path: Path = NON_CONVERGED_CSV_PATH) -> None:
        """Save non-converged VLM IDs to CSV file."""
        if not self._unassigned_vlm_ids:
            print("No non-converged entries to save.")
            return
        
        # Load VLM data for additional info
        vlm_df = load_vlm_data()
        
        # Get rows for unassigned VLM IDs
        unassigned_df = vlm_df[vlm_df["verkn_ligand_metalID"].isin(self._unassigned_vlm_ids)].copy()
        
        # Select relevant columns
        cols = [
            "verkn_ligand_metalID", "metalNr", "ligandenNr", "beta_definitionNr",
            "constanttypNr", "constant", "temperature", "ionicstrength"
        ]
        out_df = unassigned_df[[c for c in cols if c in unassigned_df.columns]]
        out_df.to_csv(path, index=False)
        print(f"Non-converged VLM IDs saved to: {path} ({len(out_df)} entries)")
    
    def save_no_species_csv(self, path: Path = NO_SPECIES_CSV_PATH) -> None:
        """Save no-species VLM IDs to CSV file."""
        if not self.debug_report.no_species_vlm_ids:
            print("No no-species entries to save.")
            return
        
        # Load VLM data for additional info
        vlm_df = load_vlm_data()
        
        # Get rows for no-species VLM IDs
        no_species_df = vlm_df[vlm_df["verkn_ligand_metalID"].isin(self.debug_report.no_species_vlm_ids)].copy()
        
        # Select relevant columns
        cols = [
            "verkn_ligand_metalID", "metalNr", "ligandenNr", "beta_definitionNr",
            "constanttypNr", "constant", "temperature", "ionicstrength"
        ]
        out_df = no_species_df[[c for c in cols if c in no_species_df.columns]]
        out_df.to_csv(path, index=False)
        print(f"No-species VLM IDs saved to: {path} ({len(out_df)} entries)")


# =============================================================================
# Main export function
# =============================================================================

def export_equilibrium_maps_to_sql(
    output_path: Path = DEFAULT_SQL_PATH,
    max_pairs: Optional[int] = None,
    max_iterations: int = 10000,
) -> Tuple[Path, DebugReport]:
    """Export all equilibrium maps to SQL database.
    
    Args:
        output_path: Path to output SQLite database
        max_pairs: Optional limit for testing
        max_iterations: Maximum iterations per pair (default 10000)
        
    Returns:
        Tuple of (database path, debug report)
    """
    logger.info(f"export_equilibrium_maps_to_sql: output={output_path}, max_pairs={max_pairs}, max_iterations={max_iterations}")
    
    exporter = EquilibriumMapSQLExporter(output_path)
    
    try:
        exporter.open()
        logger.info("export_equilibrium_maps_to_sql: Database opened")
        
        report = exporter.export_all(max_pairs, max_iterations)
        exporter.save_debug_report()
        exporter.save_no_species_csv()
        
        # Save non-converged entries if any
        if report.vlm_unassigned > 0:
            exporter.save_non_converged_csv()
        
        logger.info(f"export_equilibrium_maps_to_sql: Export complete - coverage={report.vlm_assigned_to_networks}/{report.total_vlm_k_type}")
        
        print(f"\n{'='*60}")
        print("Export complete!")
        print(f"{'='*60}")
        print(f"Database: {output_path}")
        print(f"Total VLM (K-type): {report.total_vlm_k_type}")
        print(f"No-species (skipped): {report.no_species_vlm_count}")
        print(f"Assigned to networks: {report.vlm_assigned_to_networks}")
        print(f"Stray (duplicates): {report.vlm_stray}")
        print(f"Unassigned (non-converged): {report.vlm_unassigned}")
        coverage = report.vlm_assigned_to_networks / (report.total_vlm_k_type - report.no_species_vlm_count) * 100 if (report.total_vlm_k_type - report.no_species_vlm_count) > 0 else 0
        print(f"Coverage rate (excl. no-species): {coverage:.1f}%")
        print(f"Duration: {report.duration_seconds:.1f}s")
        print(f"{'='*60}")
        
        return output_path, report
        
    finally:
        exporter.close()


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Equilibrium Map SQL Exporter")
    parser.add_argument("--debug", action="store_true", help="Enable DEBUG level logging")
    parser.add_argument("--log-file", type=str, help="Path to log file")
    parser.add_argument("--max-pairs", type=int, help="Limit number of pairs to process (for testing)")
    args = parser.parse_args()
    
    # Setup logging
    log_level = logging.DEBUG if args.debug else logging.INFO
    log_file = Path(args.log_file) if args.log_file else OUTPUT_DIR / "equilibrium_map_export.log"
    setup_logging(level=log_level, log_file=log_file)
    
    # Also setup logging for the builder module
    from equilibrium_map_builder_v3 import setup_logging as builder_setup_logging
    builder_setup_logging(level=log_level, log_file=log_file)
    
    print("Equilibrium Map SQL Exporter")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Log file: {log_file}")
    logger.info(f"Starting Equilibrium Map SQL Exporter")
    
    # Run full export
    db_path, report = export_equilibrium_maps_to_sql(max_pairs=args.max_pairs)
    
    logger.info(f"Export complete. Database: {db_path}")
    print("\nDone!")
