"""Chemistry rule families with one shared registry and a stable public API.

Edit the owning family module. Existing pipeline and legacy parser imports may
continue to use ``srd46_pipeline.manual_rules``. Ledger identifiers intentionally
remain ``manual_rules.<RULE-ID>`` so historical audits remain comparable.
"""
from ..paths import PROJECT_ROOT
from .registry import *  # noqa: F401,F403 - intentional public re-export
from .sources import *  # noqa: F401,F403 - intentional public re-export
from .measurements import *  # noqa: F401,F403 - intentional public re-export
from .ligands import *  # noqa: F401,F403 - intentional public re-export
from .metals import *  # noqa: F401,F403 - intentional public re-export
from .hxl import *  # noqa: F401,F403 - intentional public re-export
from .policies import *  # noqa: F401,F403 - intentional public re-export
from .beta_names import *  # noqa: F401,F403 - intentional public re-export
from .beta_tokens import *  # noqa: F401,F403 - intentional public re-export
from .beta_corrections import *  # noqa: F401,F403 - intentional public re-export
from .beta_unresolved import *  # noqa: F401,F403 - intentional public re-export
from .validation import *  # noqa: F401,F403 - intentional public re-export

__all__ = [
    'PROJECT_ROOT',
    'LEDGER_SOURCE_PREFIX',
    'ledger_source',
    'Rule',
    'RULES',
    'CANONICAL_DUMP_DIR',
    'CANONICAL_DUMP_ENCODING',
    'CANONICAL_NULL_TOKEN',
    'CANONICAL_TABLE_FILES',
    'CANONICAL_EXPECTED_ROWS',
    'RAW_SOURCE_POLICY',
    'CSV_LINEAGE_TABLES',
    'CSV_LINEAGE_ALLOWED',
    'BETA_DEFINITION_VARCHAR_LIMIT',
    'EXCEL_SERIAL_EPOCH',
    'VLM_PLACEHOLDER_TOKEN',
    'VLM_PLACEHOLDER_EXPECTED',
    'VLM_PLACEHOLDER_NOTE',
    'VLM_PAREN_RE',
    'VLM_PAREN_NOTE',
    'VLM_TEMPERATURE_SUFFIX',
    'VLM_TV_NOTE',
    'VLM_NUMERIC_FIELDS',
    'VlmMetalCorrection',
    'VLM_SOURCE_FIELDS',
    'VlmSourceReview',
    'VLM_SOURCE_REVIEWS',
    'VLM_SOURCE_REVIEW_NOTE',
    'VLM_SOURCE_REVIEW_EQUATION',
    'VLM_SOURCE_REVIEW_REFERENCES',
    'validate_vlm_source_review_rows',
    'VLM_METAL_CORRECTIONS',
    'corrected_vlm_metal_id',
    'validate_vlm_metal_correction_rows',
    'PARSER_NOTE_PREFIX',
    'PARSER_NOTE_KEYS',
    'PARSER_NOTE_RE',
    'PARSER_NOTE_RULE_JOINER',
    'PLACEHOLDER_NOTE',
    'parser_note',
    'parse_parser_notes',
    'vlm_parser_notes',
    'LIGAND_PLACEHOLDER_SQL',
    'MEASURED_PLACEHOLDER_SQL',
    'PLACEHOLDER_SPLIT_QUERIES',
    'ACCEPTED_ROWS_ON_PLACEHOLDER_LIGANDS_SQL',
    'PLACEHOLDER_CONSTANT_TYPE_SQL',
    'parse_vlm_number',
    'derive_vlm_fields',
    'PARSER_NOTES_DOC',
    'LIG01_COUNTER_ION_WORDS',
    'LIG01_IDENTITY_DESCRIPTORS',
    'LIG01_REJECT_MULTI_FRAGMENT',
    'LIG01_EXCLUDE_NAMES',
    'LIGAND_NAME_VARIANT_RULES',
    'ligand_name_variants',
    'ligand_variant_source',
    'ligand_variant_structure_ok',
    'PinnedLookup',
    'LIG01_PINNED_LOOKUPS',
    'ligand_pinned_source',
    'desalt_to_parent',
    'StereoStructure',
    'LIG03_STEREO_STRUCTURES',
    'ligand_stereo_source',
    'stereo_molblock',
    'LIGAND_PLACEHOLDER_FIGURE',
    'LIGAND_STRUCTURE_PLACEHOLDERS',
    'ligand_placeholder_fields',
    'ligand_is_placeholder',
    'LIG02_TRIGGER_SUBSTRING',
    'LIG02_CACHE_PREFIX',
    'PUBCHEM_NAME_PROPERTY_URL',
    'MetalSmiles',
    'METAL_SMILES_MANUAL',
    'METAL_SMILES_PARSE_NOTE',
    'metal_charge_from_name',
    'MET02_ORGANIC_SUBSTITUENTS',
    'HXL01_COUNTERION_TEMPLATES',
    'HXL02_DESALTED_CATION_NAME_TOKENS',
    'HXL03_SUPERATOM_FIGURES',
    'PinnedFigure',
    'HXL04_PINNED_FIGURES',
    'REF01_TEMPERATURE_C',
    'REF01_TEMPERATURE_TOLERANCE_C',
    'REF01_IONIC_STRENGTH_M',
    'REF01_IONIC_STRENGTH_TOLERANCE_M',
    'REF01_HPLUS_METAL_ID',
    'REF01_CONSTANT_TYPE_K',
    'QUP01_ONLY_IDS_WITHOUT_SDF',
    'BETA02_TEXT_REPLACEMENTS',
    'BetaNameFix',
    'BETA_NAME_FIXES',
    'BETA02_LEGACY_IDS',
    'BetaOrphanRow',
    'BETA_ORPHAN_ROW_FILLS',
    'beta_name_fixes_legacy',
    'BETA_POLYMETAL_HOL_TOKENS',
    'BETA03_NOTES_WITH_WRONG_ANNOTATIONS',
    'BALANCED',
    'UNBALANCED',
    'BetaCorrection',
    'BETA_EQUATION_CORRECTIONS',
    'BETA03_SUPERSEDED_BY_BETA02',
    'BETA03_SUPERSEDED_BY_BETA04',
    'BETA03_REVISED',
    'beta_equation_corrections_legacy',
    'BETA_KNOWN_UNPARSEABLE',
    'BETA_UNRESOLVED_CANDIDATES',
    'BETA_ORPHAN_VERKN_REFS',
    'beta_known_category',
    'validate',
    'describe',
]
