"""
csv_atlas_loader.py — Load Pourbaix atlas species from the pre-parsed CSV.
==========================================================================
Provides the same ``AtlasSpecies`` objects as ``atlas_parser.py``, but
reads from the bulk CSV (``pourbaix_substances_all.csv``) rather than
re-parsing individual ``.md`` files.

The CSV was generated by ``parse_pourbaix_substances.py`` and already
contains ``mu0_kJ`` (kJ/mol, the unit used by the Pourbaix calculator).

Public API
----------
    load_csv_atlas(csv_path=None)
        → dict[str, list[AtlasSpecies]]        (element name → species)

    atlas_species_for_element(element, csv_path=None)
        → list[AtlasSpecies]

    list_csv_elements(csv_path=None)
        → list[str]
"""
from __future__ import annotations

import csv
import logging
import math
import re
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional

from .atlas_data import AtlasSpecies, _SYMBOL_TO_NAME

log = logging.getLogger("CSVAtlasLoader")


def _find_aux_csv() -> Path:
    """Locate the cleaned atlas CSV by walking up to ``Auxillary_dbs_storage``.

    Robust to directory reshuffles: searches ancestors for a folder
    named ``Auxillary_dbs_storage`` rather than counting path levels.
    """
    here = Path(__file__).resolve()
    rel = Path("Auxillary_dbs_storage") / "Pourbaix_atlas_database" / "_pourbaix_substances_all.csv"
    for parent in here.parents:
        cand = parent / rel
        if cand.exists():
            return cand
    # Fall back to the conventional repo-root location even if missing,
    # so the loader's FileNotFoundError names the expected path.
    return here.parents[6] / rel


_DEFAULT_CSV = _find_aux_csv()


# ══════════════════════════════════════════════════════════════
#  CSV loading (cached)
# ══════════════════════════════════════════════════════════════

@lru_cache(maxsize=4)
def _load_csv(csv_path: str) -> Dict[str, List[AtlasSpecies]]:
    """Load and index the CSV by *sub_element* (element name).

    Returns a dict mapping element name (e.g. "Iron", "Copper") to a
    list of ``AtlasSpecies``.
    """
    p = Path(csv_path)
    if not p.exists():
        raise FileNotFoundError(f"Atlas CSV not found: {p}")

    by_element: Dict[str, List[AtlasSpecies]] = {}

    with p.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            mu0_raw = row.get("mu0_cal", "")
            if not mu0_raw:
                continue
            try:
                mu0_cal = float(mu0_raw)
            except ValueError:
                continue

            sub_el = row.get("sub_element", row.get("element", ""))
            source_file = row.get("file", "")

            sp = AtlasSpecies(
                phase=row.get("phase", ""),
                species=row.get("species", ""),
                oxidation_state=row.get("oxidation_state", ""),
                mu0_cal=mu0_cal,
                name=row.get("name", ""),
                element=sub_el,
                source_file=Path(source_file).stem if source_file else "",
            )
            by_element.setdefault(sub_el, []).append(sp)

    log.info("Loaded %d elements, %d total species from %s",
             len(by_element),
             sum(len(v) for v in by_element.values()),
             p.name)
    return by_element


# ══════════════════════════════════════════════════════════════
#  Public API
# ══════════════════════════════════════════════════════════════

def load_csv_atlas(
    csv_path: Optional[str | Path] = None,
) -> Dict[str, List[AtlasSpecies]]:
    """Load the full CSV atlas, indexed by element name.

    Parameters
    ----------
    csv_path : path to ``pourbaix_substances_all.csv``
               (auto-detected if None)

    Returns
    -------
    Dict mapping element name (e.g. "Iron") to list of AtlasSpecies.
    """
    return _load_csv(str(csv_path or _DEFAULT_CSV))


def _resolve_element_name(element: str) -> str:
    """Resolve a chemical symbol or name to the atlas element name.

    Accepts "Fe", "Iron", "iron", "FE" etc.
    """
    stripped = element.strip()
    # Try symbol lookup first
    resolved = _SYMBOL_TO_NAME.get(stripped)
    if resolved:
        return resolved
    # Try case-insensitive match against known names
    # (reverse map: lowered name → canonical name)
    name_lower = stripped.lower()
    for sym, name in _SYMBOL_TO_NAME.items():
        if name.lower() == name_lower:
            return name
    # Return as-is (will be looked up against CSV keys directly)
    return stripped


_ROMAN_OX = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    "V": 5,
    "VI": 6,
    "VII": 7,
    "VIII": 8,
    "IX": 9,
    "X": 10,
}

_QUALIFIED_OX_RE = re.compile(
    r'([+-]?(?:\d+(?:\.\d+)?(?:/\d+)?|[IVX]+))'
    r'\s*\(([A-Z][a-z]?)\)',
)


def _element_symbol(element: Optional[str]) -> Optional[str]:
    """Resolve an Atlas element symbol/name to a canonical symbol."""
    stripped = str(element or "").strip()
    for symbol, name in _SYMBOL_TO_NAME.items():
        if stripped.casefold() in {symbol.casefold(), name.casefold()}:
            return symbol
    return None


def _one_ox_state_value(token: str) -> Optional[float]:
    """Parse one Arabic, Roman, decimal, or rational oxidation value."""
    clean = token.strip()
    sign = 1
    if clean.startswith(("+", "-")):
        if clean[0] == "-":
            sign = -1
        clean = clean[1:].strip()

    roman = _ROMAN_OX.get(clean.upper())
    if roman is not None and clean.isalpha():
        return float(sign * roman)

    fraction = re.fullmatch(r'(\d+)\s*/\s*(\d+)', clean)
    if fraction:
        denominator = int(fraction.group(2))
        if denominator == 0:
            return None
        return sign * int(fraction.group(1)) / denominator

    try:
        value = sign * float(clean)
    except ValueError:
        return None
    return value if math.isfinite(value) else None


def _ox_state_values(
    ox_raw: str,
    central_element: Optional[str] = None,
) -> List[float]:
    """Parse numeric values from an Atlas oxidation-state cell.

    Handles integer, decimal, Roman, comma/slash mixed-valence, and rational
    average spellings.  For element-qualified cells such as
    ``+2 (Ba), -1 (O)``, only the central element's value is used when the
    row element is known.  A cell that labels only another element, such as
    ``-1 (H)`` on ``BaH2``, is left unresolved rather than misclassifying the
    metal as negative.
    """
    raw = str(ox_raw or "").strip()
    qualified = _QUALIFIED_OX_RE.findall(raw)
    symbol = _element_symbol(central_element)
    if qualified and symbol:
        selected = [
            token
            for token, element in qualified
            if element.casefold() == symbol.casefold()
        ]
        if not selected:
            return []
        tokens = selected
    elif qualified:
        tokens = [token for token, _ in qualified]
    else:
        clean = re.sub(
            r'\s*\(\s*mixed\s*\)\s*$',
            '',
            raw,
            flags=re.IGNORECASE,
        )
        # ``+3/+4`` is a state list; ``+8/3`` is a rational average.
        clean = re.sub(r'/\s*(?=[+-])', ',', clean)
        tokens = clean.replace(";", ",").split(",")

    out: List[float] = []
    for token in tokens:
        value = _one_ox_state_value(token)
        if value is not None:
            out.append(value)
    return out


def _is_physical_aqueous_atlas_species(sp: AtlasSpecies) -> bool:
    """Reject non-physical atlas entries for aqueous/Pourbaix modelling.

    The Pourbaix atlas carries gas-phase molecules (e.g. ``CuH``) and
    exotic negative metal oxidation states (e.g. ``Cu(-1)``) that have no
    place in an aqueous speciation / Pourbaix card. Including them adds a
    phantom gas species and a non-existent reduced metal state to every
    enriched card.

    Keeps:
      * any non-gas phase (aqueous / dissolution / solid), and
      * oxidation state 0 (the metal itself) and all positive states,
        plus mixed-valence cells where any component is >= 0.
    Drops:
      * gas-phase entries (``phase`` starts with "gas", e.g. the CSV's
        ``Gaseous``), and
      * strictly-negative single oxidation states.
    """
    if str(getattr(sp, "phase", "")).strip().lower().startswith("gas"):
        return False
    ox_vals = _ox_state_values(
        getattr(sp, "oxidation_state", ""),
        central_element=getattr(sp, "element", ""),
    )
    if ox_vals and all(v < 0 for v in ox_vals):
        return False
    return True


def atlas_species_for_element(
    element: str,
    csv_path: Optional[str | Path] = None,
    *,
    physical_only: bool = True,
) -> List[AtlasSpecies]:
    """Return all Pourbaix atlas species for a given element.

    Parameters
    ----------
    element  : element name ("Iron", "Copper") or symbol ("Fe", "Cu")
    csv_path : optional CSV path override
    physical_only : when True (default), drop gas-phase entries and
        strictly-negative metal oxidation states (see
        :func:`_is_physical_aqueous_atlas_species`) so the enriched card
        only carries species meaningful for aqueous/Pourbaix modelling.

    Returns
    -------
    List[AtlasSpecies], empty if element not found.
    """
    by_el = load_csv_atlas(csv_path)
    resolved = _resolve_element_name(element)

    species = by_el.get(resolved, [])
    if not species:
        # Fallback: case-insensitive scan of all keys
        for key, vals in by_el.items():
            if key.lower() == resolved.lower():
                species = vals
                break
    if physical_only:
        species = [s for s in species if _is_physical_aqueous_atlas_species(s)]
    return species


def list_csv_elements(
    csv_path: Optional[str | Path] = None,
) -> List[str]:
    """List all element names available in the CSV atlas."""
    return sorted(load_csv_atlas(csv_path).keys())
